version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - 'NEO4J_AUTH=neo4j/your_password'
      - 'NEO4JLABS_PLUGINS=["apoc"]'
      - 'NEO4J_apoc_export_file_enabled=true'
      - 'NEO4J_apoc_import_file_enabled=true'
      - 'NEO4J_dbms_security_procedures_unrestricted=apoc.*'
      - 'NEO4J_dbms_security_procedures_allowlist=apoc.*'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - neo4j
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  rag:
    build:
      context: ./rag
    depends_on:
      - neo4j
      - ollama
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=your_password
    ports:
      - "5000:5000"
    volumes:
      - ./rag:/rag
    networks:
      - app-network
    restart: always

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ollama_with_llama2
    container_name: ollama_container
    environment:
      - MODELS_DIR=/models
      - OLLAMA_HOST=0.0.0.0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/models
    restart: always
    networks:
      - app-network

volumes:
  neo4j-data: 

networks:
  app-network:
    driver: bridge
